import Foundation

/// The caveat strings are part of the product contract. They are baked into
/// every verdict so that a negative result can never be mistaken for proof of
/// human authorship, and a positive result can never be mistaken for proof of
/// AI authorship.
public enum Caveats {
    public static let textNegative =
        "No watermark detected. This does not prove human authorship; Claude output may carry no mark if it was edited, paraphrased, translated, or generated by an earlier model."

    public static let textTooShort =
        "The passage is too short for a reliable watermark signal. This does not prove human authorship; short or heavily edited passages carry no reliable signal."

    public static func textPositive(confidenceLabel: String) -> String {
        "A Claude watermark was detected with \(confidenceLabel) confidence. This means Claude likely processed this text; it is not proof of AI authorship."
    }

    public static func fileValid(signer: String?, tool: String?) -> String {
        let signerName = signer ?? "an unknown entity"
        let toolName = tool ?? "an unknown tool"
        return "This file was signed by \(signerName) using \(toolName). It has not been modified since signing."
    }

    public static func fileModified(tool: String?) -> String {
        let toolName = tool ?? "the signer"
        return "This file was modified after \(toolName) processed it."
    }

    public static let fileNoManifest =
        "No C2PA metadata found. This does not prove human authorship; the metadata may have been stripped by a re-save, a format conversion, or an upload pipeline."

    public static let general =
        "A detected mark means Claude likely processed the content. It is not proof of AI authorship, and no mark does not prove human authorship."

    public static let detectionNotAvailable =
        "Anthropic has not yet released its detection API or the watermark detection parameters. Until it ships, an honest text verdict is not possible."
}
