import Foundation

/// The caveat strings are part of the product contract. They are baked into
/// every verdict so that a negative result can never be mistaken for proof of
/// human authorship, and a positive result can never be mistaken for proof of
/// AI authorship.
public enum Caveats {
    public static let textNegative =
        "No AI-typical pattern was detected. This does not prove human authorship; AI output may carry no detectable signal if it was edited, paraphrased, translated, or generated by a model the detectors cannot read."

    public static let textTooShort =
        "The passage is too short for a reliable signal. This does not prove human authorship; short or heavily edited passages carry no reliable signal."

    public static func textPositive(confidenceLabel: String) -> String {
        "An AI-generation pattern was detected with \(confidenceLabel) confidence. This means the text's statistical shape resembles AI-generated prose; it is not proof of AI authorship."
    }

    /// Caveat for a positive signal from the local statistical heuristic.
    /// The heuristic is a pattern detector, not the released Anthropic
    /// watermark detector, so the wording must not claim the watermark.
    public static func textPositiveHeuristic(confidenceLabel: String) -> String {
        "The local detector found AI-typical writing patterns with \(confidenceLabel) confidence. It is a statistical heuristic (uniformity, repetition, vocabulary, phrasing), not Anthropic's watermark detector, which has not been released. Treat it as a signal, not proof, for any model family."
    }

    /// Caveat for a negative signal from the local statistical heuristic.
    public static let textNegativeHeuristic =
        "The local detector found no AI-typical patterns. This does not prove human authorship: it is a statistical assessment, not the official watermark detector."

    public static let textInconclusive =
        "The statistical signals did not resolve to a clear pattern. This is not proof either way."

    public static func fileValid(signer: String?, tool: String?) -> String {
        let signerName = signer ?? "an unknown entity"
        let toolName = tool ?? "an unknown tool"
        return "This file was signed by \(signerName) using \(toolName). It has not been modified since signing."
    }

    /// Used by the built-in verifier when it proved the claim signature but
    /// could not recompute the file content hash: the claim is authentic,
    /// but the file itself may have changed since signing.
    public static func fileValidClaimOnly(signer: String?, tool: String?) -> String {
        let signerName = signer ?? "an unknown entity"
        let toolName = tool ?? "an unknown tool"
        return "The embedded provenance claim was signed by \(signerName) using \(toolName), and the Ed25519 signature verifies. The file's content hash is not checked without c2patool, so the file may have changed since signing."
    }
    public static func fileModified(tool: String?) -> String {
        let toolName = tool ?? "the signer"
        return "This file was modified after \(toolName) processed it."
    }

    public static let fileNoManifest =
        "No C2PA metadata found. This does not prove human authorship; the metadata may have been stripped by a re-save, a format conversion, or an upload pipeline."

    public static let general =
        "A detected signal means the content shows AI-generation characteristics. It is not proof of AI authorship, and no signal does not prove human authorship."

    public static let detectionNotAvailable =
        "No detection provider could produce an honest verdict. If you disabled the local detector, re-enable it in Settings; the Anthropic detection API is also not yet released."
}
