#!/bin/bash
# Generates the structured release notes for a GitHub release.
# Usage: sh Scripts/release-notes.sh <version> [checksum]
set -euo pipefail

VERSION="${1:?version required}"
CHECKSUM="${2:-}"

SINCE="$(git describe --tags --abbrev=0 2>/dev/null || true)"
CHANGES=""
if [[ -n "${SINCE}" ]]; then
  CHANGES="$(git log --oneline --no-decorate "${SINCE}..HEAD" 2>/dev/null | sed 's/^/- /' || true)"
fi
if [[ -z "${CHANGES}" ]]; then
  CHANGES="- Initial release of the engine and the macOS app."
fi

cat <<EOF
# OriginCheck ${VERSION}

OriginCheck answers one question: was this text or file generated by Claude? It verifies C2PA provenance metadata on media files today, and reports the honest unavailable state for text watermark detection until Anthropic ships its detection API.

## What changed

${CHANGES}

## The artifact

- File: OriginCheck-${VERSION}.dmg
- Platform: macOS 14 or later, Apple Silicon and Intel
- SHA-256: \`${CHECKSUM:-computed at build time and printed in the build log}\`
- Signed for updates with Sparkle's EdDSA key. Updates are verified against the published signature before they are installed.

## Install

1. Download OriginCheck-${VERSION}.dmg and open it.
2. Drag OriginCheck.app into the Applications folder.
3. Right-click the app and choose Open the first time. This build is ad-hoc signed, so macOS asks once.
4. For file verification, install c2patool once: \`cargo install c2patool\`. Text checks work without it and report the honest unavailable state.

## Automatic updates

The app checks the update feed in the background and can download and install future releases through Sparkle. Updates are never installed without your approval, and your preferences and history survive every update.

## Supported formats

png, jpg, jpeg, svg, webp, avif, heic, heif, tif, tiff, dng, mp4, mov, m4a, mp3, wav, pdf (read-only).

## Privacy

Everything runs locally. No telemetry, no accounts, no cloud. History stores a SHA-256 hash of your input unless you explicitly consent to keeping the raw content.

## Known limits

- Text watermark detection is not available yet. Anthropic announced the API but has not released it. The app says so instead of guessing.
- The app is not notarized yet. Notarization needs an Apple Developer certificate and will be wired in when one is available.

## Build from source

\`\`\`
swift test
cd App && swift build -c release
sh Scripts/package-app.sh <version> <build> .
sh Scripts/make-dmg.sh <version> .
\`\`\`
EOF
