#!/usr/bin/env python3
"""Insert a new <item> into appcast.xml for an OriginCheck release.

Called by the release pipeline after the DMG is built and signed with
Sparkle's sign_update. Keeps every previous <item> (Sparkle walks the whole
feed to offer intermediate updates), inserting the new one first since
Sparkle expects the newest release at the top.

Idempotent: if an enclosure with the same build number already exists, this
script does nothing, so a partially failed release can be retried safely.

Environment:
  APPCAST_PATH        path to appcast.xml
  RELEASE_VERSION     marketing version, e.g. 1.2.0
  BUILD               build number, e.g. 20260815120000
  ED_SIGNATURE        sparkle:edSignature of the exact DMG being published
  LENGTH              byte length of that same DMG
  DOWNLOAD_URL        direct download URL of the DMG attached to the release
  MIN_SYSTEM_VERSION  optional, defaults to 14.0
"""
import os
import sys
import xml.etree.ElementTree as ET
from datetime import datetime, timezone

SPARKLE_NS = "http://www.andymatuschak.org/xml-namespaces/sparkle"
ET.register_namespace("sparkle", SPARKLE_NS)
ET.register_namespace("dc", "http://purl.org/dc/elements/1.1/")

HEADER_COMMENT = """<!--
  OriginCheck update feed (Sparkle).

  Do not edit this file by hand. It is regenerated by
  Scripts/update-appcast.py during every release. The SUPublicEDKey in the
  app's Info.plist must match the key that signed every enclosure here.
-->
"""


def sparkle_tag(name: str) -> str:
    return f"{{{SPARKLE_NS}}}{name}"


def main() -> None:
    path = os.environ["APPCAST_PATH"]
    version = os.environ["RELEASE_VERSION"]
    build = os.environ["BUILD"]
    ed_signature = os.environ["ED_SIGNATURE"]
    length = os.environ["LENGTH"]
    download_url = os.environ["DOWNLOAD_URL"]
    min_system_version = os.environ.get("MIN_SYSTEM_VERSION", "14.0")

    tree = ET.parse(path)
    channel = tree.getroot().find("channel")
    if channel is None:
        raise SystemExit("appcast.xml has no <channel> element")

    # Idempotency: never insert the same build twice, and replace any prior
    # entry for the same marketing version. A retried release rebuilds the
    # DMG with a fresh build number and signature, so an old entry for the
    # same version would point at the same download URL with a signature
    # that no longer matches the published artifact.
    for item in channel.findall("item"):
        enclosure = item.find("enclosure")
        if enclosure is None:
            continue
        if enclosure.get(sparkle_tag("version")) == build:
            print(f"appcast entry for build {build} already exists; skipping")
            return
        if enclosure.get(sparkle_tag("shortVersionString")) == version:
            channel.remove(item)
            print(f"removed stale appcast entry for version {version}")

    item = ET.Element("item")

    title = ET.SubElement(item, "title")
    title.text = f"Version {version}"

    pub_date = ET.SubElement(item, "pubDate")
    pub_date.text = datetime.now(timezone.utc).strftime("%a, %d %b %Y %H:%M:%S +0000")

    min_os = ET.SubElement(item, sparkle_tag("minimumSystemVersion"))
    min_os.text = min_system_version

    enclosure = ET.SubElement(item, "enclosure")
    enclosure.set("url", download_url)
    enclosure.set("type", "application/octet-stream")
    enclosure.set(sparkle_tag("version"), build)
    enclosure.set(sparkle_tag("shortVersionString"), version)
    enclosure.set(sparkle_tag("edSignature"), ed_signature)
    enclosure.set("length", length)

    # Newest first: insert before the first existing <item>, or append if
    # this is the very first release entry.
    children = list(channel)
    existing_items = [i for i, child in enumerate(children) if child.tag == "item"]
    insert_at = existing_items[0] if existing_items else len(children)
    channel.insert(insert_at, item)

    # ElementTree drops comments on write, so re-add the header comment by
    # writing the XML body first and prepending the declaration manually.
    body = ET.tostring(tree.getroot(), encoding="unicode")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write('<?xml version="1.0" encoding="utf-8"?>\n')
        fh.write(HEADER_COMMENT)
        fh.write(body)
        fh.write("\n")

    print(f"Added appcast entry for {version} (build {build})")


if __name__ == "__main__":
    main()
